FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/web/package.json ./apps/web/
RUN npm install

COPY . .

WORKDIR /app/apps/web

RUN chown -R node:node /app

USER node

EXPOSE 3000
CMD ["npx", "next", "dev", "-H", "0.0.0.0"]
