FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/api-nest/package.json ./apps/api-nest/
RUN apk add --no-cache openssl
RUN npm install

COPY . .
RUN mkdir -p /app/apps/api-nest/uploads

WORKDIR /app/apps/api-nest

EXPOSE 3002
RUN chmod +x /app/apps/api-nest/docker-entrypoint.dev.sh
ENTRYPOINT ["/app/apps/api-nest/docker-entrypoint.dev.sh"]
