"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Course = void 0;
const typeorm_1 = require("typeorm");
const Simulation_1 = require("./Simulation");
const Scenario_1 = require("./Scenario");
const Assessment_1 = require("./Assessment");
const CourseModule_1 = require("./CourseModule");
const TelemetryLog_1 = require("./TelemetryLog");
const CourseConfig_1 = require("./CourseConfig");
const SimulationInstance_1 = require("./SimulationInstance");
const MinistryRequirement_1 = require("./MinistryRequirement");
const KPI_1 = require("./KPI");
const Task_1 = require("./Task");
let Course = (() => {
    let _classDecorators = [(0, typeorm_1.Entity)('courses'), (0, typeorm_1.Index)(['course_id'], { unique: true }), (0, typeorm_1.Index)(['category'])];
    let _classDescriptor;
    let _classExtraInitializers = [];
    let _classThis;
    let _id_decorators;
    let _id_initializers = [];
    let _id_extraInitializers = [];
    let _course_id_decorators;
    let _course_id_initializers = [];
    let _course_id_extraInitializers = [];
    let _title_decorators;
    let _title_initializers = [];
    let _title_extraInitializers = [];
    let _description_decorators;
    let _description_initializers = [];
    let _description_extraInitializers = [];
    let _category_decorators;
    let _category_initializers = [];
    let _category_extraInitializers = [];
    let _categories_decorators;
    let _categories_initializers = [];
    let _categories_extraInitializers = [];
    let _modules_decorators;
    let _modules_initializers = [];
    let _modules_extraInitializers = [];
    let _ai_config_decorators;
    let _ai_config_initializers = [];
    let _ai_config_extraInitializers = [];
    let _eval_criteria_decorators;
    let _eval_criteria_initializers = [];
    let _eval_criteria_extraInitializers = [];
    let _crisis_events_decorators;
    let _crisis_events_initializers = [];
    let _crisis_events_extraInitializers = [];
    let _simulated_company_id_decorators;
    let _simulated_company_id_initializers = [];
    let _simulated_company_id_extraInitializers = [];
    let _is_active_decorators;
    let _is_active_initializers = [];
    let _is_active_extraInitializers = [];
    let _created_by_decorators;
    let _created_by_initializers = [];
    let _created_by_extraInitializers = [];
    let _created_at_decorators;
    let _created_at_initializers = [];
    let _created_at_extraInitializers = [];
    let _updated_at_decorators;
    let _updated_at_initializers = [];
    let _updated_at_extraInitializers = [];
    let _config_decorators;
    let _config_initializers = [];
    let _config_extraInitializers = [];
    let _simulations_decorators;
    let _simulations_initializers = [];
    let _simulations_extraInitializers = [];
    let _scenarios_decorators;
    let _scenarios_initializers = [];
    let _scenarios_extraInitializers = [];
    let _assessments_decorators;
    let _assessments_initializers = [];
    let _assessments_extraInitializers = [];
    let _course_modules_decorators;
    let _course_modules_initializers = [];
    let _course_modules_extraInitializers = [];
    let _telemetry_logs_decorators;
    let _telemetry_logs_initializers = [];
    let _telemetry_logs_extraInitializers = [];
    let _simulation_instances_decorators;
    let _simulation_instances_initializers = [];
    let _simulation_instances_extraInitializers = [];
    let _ministry_requirements_decorators;
    let _ministry_requirements_initializers = [];
    let _ministry_requirements_extraInitializers = [];
    let _kpis_decorators;
    let _kpis_initializers = [];
    let _kpis_extraInitializers = [];
    let _tasks_decorators;
    let _tasks_initializers = [];
    let _tasks_extraInitializers = [];
    var Course = _classThis = class {
        constructor() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.course_id = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _course_id_initializers, void 0));
            this.title = (__runInitializers(this, _course_id_extraInitializers), __runInitializers(this, _title_initializers, void 0));
            this.description = (__runInitializers(this, _title_extraInitializers), __runInitializers(this, _description_initializers, void 0));
            this.category = (__runInitializers(this, _description_extraInitializers), __runInitializers(this, _category_initializers, void 0));
            this.categories = (__runInitializers(this, _category_extraInitializers), __runInitializers(this, _categories_initializers, void 0));
            this.modules = (__runInitializers(this, _categories_extraInitializers), __runInitializers(this, _modules_initializers, void 0));
            this.ai_config = (__runInitializers(this, _modules_extraInitializers), __runInitializers(this, _ai_config_initializers, void 0));
            this.eval_criteria = (__runInitializers(this, _ai_config_extraInitializers), __runInitializers(this, _eval_criteria_initializers, void 0));
            this.crisis_events = (__runInitializers(this, _eval_criteria_extraInitializers), __runInitializers(this, _crisis_events_initializers, void 0));
            // ⚠️ Removed: tech_sheet_id. Use TechSheet.course_id instead (N:1 relationship)
            // @Column({ type: 'int', nullable: true })
            // tech_sheet_id?: number | null;
            this.simulated_company_id = (__runInitializers(this, _crisis_events_extraInitializers), __runInitializers(this, _simulated_company_id_initializers, void 0));
            this.is_active = (__runInitializers(this, _simulated_company_id_extraInitializers), __runInitializers(this, _is_active_initializers, void 0));
            this.created_by = (__runInitializers(this, _is_active_extraInitializers), __runInitializers(this, _created_by_initializers, void 0));
            this.created_at = (__runInitializers(this, _created_by_extraInitializers), __runInitializers(this, _created_at_initializers, void 0));
            this.updated_at = (__runInitializers(this, _created_at_extraInitializers), __runInitializers(this, _updated_at_initializers, void 0));
            // Relations
            this.config = (__runInitializers(this, _updated_at_extraInitializers), __runInitializers(this, _config_initializers, void 0));
            this.simulations = (__runInitializers(this, _config_extraInitializers), __runInitializers(this, _simulations_initializers, void 0));
            this.scenarios = (__runInitializers(this, _simulations_extraInitializers), __runInitializers(this, _scenarios_initializers, void 0));
            this.assessments = (__runInitializers(this, _scenarios_extraInitializers), __runInitializers(this, _assessments_initializers, void 0));
            this.course_modules = (__runInitializers(this, _assessments_extraInitializers), __runInitializers(this, _course_modules_initializers, void 0));
            this.telemetry_logs = (__runInitializers(this, _course_modules_extraInitializers), __runInitializers(this, _telemetry_logs_initializers, void 0));
            this.simulation_instances = (__runInitializers(this, _telemetry_logs_extraInitializers), __runInitializers(this, _simulation_instances_initializers, void 0));
            this.ministry_requirements = (__runInitializers(this, _simulation_instances_extraInitializers), __runInitializers(this, _ministry_requirements_initializers, void 0));
            this.kpis = (__runInitializers(this, _ministry_requirements_extraInitializers), __runInitializers(this, _kpis_initializers, void 0));
            this.tasks = (__runInitializers(this, _kpis_extraInitializers), __runInitializers(this, _tasks_initializers, void 0));
            __runInitializers(this, _tasks_extraInitializers);
        }
    };
    __setFunctionName(_classThis, "Course");
    (() => {
        const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _course_id_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 100, unique: true })];
        _title_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 255 })];
        _description_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _category_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 100 })];
        _categories_decorators = [(0, typeorm_1.Column)({ type: 'json', nullable: true })];
        _modules_decorators = [(0, typeorm_1.Column)({ type: 'json', nullable: true })];
        _ai_config_decorators = [(0, typeorm_1.Column)({ type: 'json', nullable: true })];
        _eval_criteria_decorators = [(0, typeorm_1.Column)({ type: 'json', nullable: true })];
        _crisis_events_decorators = [(0, typeorm_1.Column)({ type: 'json', nullable: true })];
        _simulated_company_id_decorators = [(0, typeorm_1.Column)({ type: 'int', nullable: true })];
        _is_active_decorators = [(0, typeorm_1.Column)({ type: 'boolean', default: true })];
        _created_by_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 36, nullable: true })];
        _created_at_decorators = [(0, typeorm_1.CreateDateColumn)()];
        _updated_at_decorators = [(0, typeorm_1.UpdateDateColumn)()];
        _config_decorators = [(0, typeorm_1.OneToOne)(() => CourseConfig_1.CourseConfig, config => config.course)];
        _simulations_decorators = [(0, typeorm_1.OneToMany)(() => Simulation_1.Simulation, simulation => simulation.course)];
        _scenarios_decorators = [(0, typeorm_1.OneToMany)(() => Scenario_1.Scenario, scenario => scenario.course)];
        _assessments_decorators = [(0, typeorm_1.OneToMany)(() => Assessment_1.Assessment, assessment => assessment.course)];
        _course_modules_decorators = [(0, typeorm_1.OneToMany)(() => CourseModule_1.CourseModule, courseModule => courseModule.course)];
        _telemetry_logs_decorators = [(0, typeorm_1.OneToMany)(() => TelemetryLog_1.TelemetryLog, log => log.course)];
        _simulation_instances_decorators = [(0, typeorm_1.OneToMany)(() => SimulationInstance_1.SimulationInstance, instance => instance.course)];
        _ministry_requirements_decorators = [(0, typeorm_1.OneToMany)(() => MinistryRequirement_1.MinistryRequirement, req => req.course)];
        _kpis_decorators = [(0, typeorm_1.OneToMany)(() => KPI_1.KPI, kpi => kpi.course)];
        _tasks_decorators = [(0, typeorm_1.OneToMany)(() => Task_1.Task, task => task.course)];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: obj => "id" in obj, get: obj => obj.id, set: (obj, value) => { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _course_id_decorators, { kind: "field", name: "course_id", static: false, private: false, access: { has: obj => "course_id" in obj, get: obj => obj.course_id, set: (obj, value) => { obj.course_id = value; } }, metadata: _metadata }, _course_id_initializers, _course_id_extraInitializers);
        __esDecorate(null, null, _title_decorators, { kind: "field", name: "title", static: false, private: false, access: { has: obj => "title" in obj, get: obj => obj.title, set: (obj, value) => { obj.title = value; } }, metadata: _metadata }, _title_initializers, _title_extraInitializers);
        __esDecorate(null, null, _description_decorators, { kind: "field", name: "description", static: false, private: false, access: { has: obj => "description" in obj, get: obj => obj.description, set: (obj, value) => { obj.description = value; } }, metadata: _metadata }, _description_initializers, _description_extraInitializers);
        __esDecorate(null, null, _category_decorators, { kind: "field", name: "category", static: false, private: false, access: { has: obj => "category" in obj, get: obj => obj.category, set: (obj, value) => { obj.category = value; } }, metadata: _metadata }, _category_initializers, _category_extraInitializers);
        __esDecorate(null, null, _categories_decorators, { kind: "field", name: "categories", static: false, private: false, access: { has: obj => "categories" in obj, get: obj => obj.categories, set: (obj, value) => { obj.categories = value; } }, metadata: _metadata }, _categories_initializers, _categories_extraInitializers);
        __esDecorate(null, null, _modules_decorators, { kind: "field", name: "modules", static: false, private: false, access: { has: obj => "modules" in obj, get: obj => obj.modules, set: (obj, value) => { obj.modules = value; } }, metadata: _metadata }, _modules_initializers, _modules_extraInitializers);
        __esDecorate(null, null, _ai_config_decorators, { kind: "field", name: "ai_config", static: false, private: false, access: { has: obj => "ai_config" in obj, get: obj => obj.ai_config, set: (obj, value) => { obj.ai_config = value; } }, metadata: _metadata }, _ai_config_initializers, _ai_config_extraInitializers);
        __esDecorate(null, null, _eval_criteria_decorators, { kind: "field", name: "eval_criteria", static: false, private: false, access: { has: obj => "eval_criteria" in obj, get: obj => obj.eval_criteria, set: (obj, value) => { obj.eval_criteria = value; } }, metadata: _metadata }, _eval_criteria_initializers, _eval_criteria_extraInitializers);
        __esDecorate(null, null, _crisis_events_decorators, { kind: "field", name: "crisis_events", static: false, private: false, access: { has: obj => "crisis_events" in obj, get: obj => obj.crisis_events, set: (obj, value) => { obj.crisis_events = value; } }, metadata: _metadata }, _crisis_events_initializers, _crisis_events_extraInitializers);
        __esDecorate(null, null, _simulated_company_id_decorators, { kind: "field", name: "simulated_company_id", static: false, private: false, access: { has: obj => "simulated_company_id" in obj, get: obj => obj.simulated_company_id, set: (obj, value) => { obj.simulated_company_id = value; } }, metadata: _metadata }, _simulated_company_id_initializers, _simulated_company_id_extraInitializers);
        __esDecorate(null, null, _is_active_decorators, { kind: "field", name: "is_active", static: false, private: false, access: { has: obj => "is_active" in obj, get: obj => obj.is_active, set: (obj, value) => { obj.is_active = value; } }, metadata: _metadata }, _is_active_initializers, _is_active_extraInitializers);
        __esDecorate(null, null, _created_by_decorators, { kind: "field", name: "created_by", static: false, private: false, access: { has: obj => "created_by" in obj, get: obj => obj.created_by, set: (obj, value) => { obj.created_by = value; } }, metadata: _metadata }, _created_by_initializers, _created_by_extraInitializers);
        __esDecorate(null, null, _created_at_decorators, { kind: "field", name: "created_at", static: false, private: false, access: { has: obj => "created_at" in obj, get: obj => obj.created_at, set: (obj, value) => { obj.created_at = value; } }, metadata: _metadata }, _created_at_initializers, _created_at_extraInitializers);
        __esDecorate(null, null, _updated_at_decorators, { kind: "field", name: "updated_at", static: false, private: false, access: { has: obj => "updated_at" in obj, get: obj => obj.updated_at, set: (obj, value) => { obj.updated_at = value; } }, metadata: _metadata }, _updated_at_initializers, _updated_at_extraInitializers);
        __esDecorate(null, null, _config_decorators, { kind: "field", name: "config", static: false, private: false, access: { has: obj => "config" in obj, get: obj => obj.config, set: (obj, value) => { obj.config = value; } }, metadata: _metadata }, _config_initializers, _config_extraInitializers);
        __esDecorate(null, null, _simulations_decorators, { kind: "field", name: "simulations", static: false, private: false, access: { has: obj => "simulations" in obj, get: obj => obj.simulations, set: (obj, value) => { obj.simulations = value; } }, metadata: _metadata }, _simulations_initializers, _simulations_extraInitializers);
        __esDecorate(null, null, _scenarios_decorators, { kind: "field", name: "scenarios", static: false, private: false, access: { has: obj => "scenarios" in obj, get: obj => obj.scenarios, set: (obj, value) => { obj.scenarios = value; } }, metadata: _metadata }, _scenarios_initializers, _scenarios_extraInitializers);
        __esDecorate(null, null, _assessments_decorators, { kind: "field", name: "assessments", static: false, private: false, access: { has: obj => "assessments" in obj, get: obj => obj.assessments, set: (obj, value) => { obj.assessments = value; } }, metadata: _metadata }, _assessments_initializers, _assessments_extraInitializers);
        __esDecorate(null, null, _course_modules_decorators, { kind: "field", name: "course_modules", static: false, private: false, access: { has: obj => "course_modules" in obj, get: obj => obj.course_modules, set: (obj, value) => { obj.course_modules = value; } }, metadata: _metadata }, _course_modules_initializers, _course_modules_extraInitializers);
        __esDecorate(null, null, _telemetry_logs_decorators, { kind: "field", name: "telemetry_logs", static: false, private: false, access: { has: obj => "telemetry_logs" in obj, get: obj => obj.telemetry_logs, set: (obj, value) => { obj.telemetry_logs = value; } }, metadata: _metadata }, _telemetry_logs_initializers, _telemetry_logs_extraInitializers);
        __esDecorate(null, null, _simulation_instances_decorators, { kind: "field", name: "simulation_instances", static: false, private: false, access: { has: obj => "simulation_instances" in obj, get: obj => obj.simulation_instances, set: (obj, value) => { obj.simulation_instances = value; } }, metadata: _metadata }, _simulation_instances_initializers, _simulation_instances_extraInitializers);
        __esDecorate(null, null, _ministry_requirements_decorators, { kind: "field", name: "ministry_requirements", static: false, private: false, access: { has: obj => "ministry_requirements" in obj, get: obj => obj.ministry_requirements, set: (obj, value) => { obj.ministry_requirements = value; } }, metadata: _metadata }, _ministry_requirements_initializers, _ministry_requirements_extraInitializers);
        __esDecorate(null, null, _kpis_decorators, { kind: "field", name: "kpis", static: false, private: false, access: { has: obj => "kpis" in obj, get: obj => obj.kpis, set: (obj, value) => { obj.kpis = value; } }, metadata: _metadata }, _kpis_initializers, _kpis_extraInitializers);
        __esDecorate(null, null, _tasks_decorators, { kind: "field", name: "tasks", static: false, private: false, access: { has: obj => "tasks" in obj, get: obj => obj.tasks, set: (obj, value) => { obj.tasks = value; } }, metadata: _metadata }, _tasks_initializers, _tasks_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Course = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Course = _classThis;
})();
exports.Course = Course;
