FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package.json package-lock.json ./

COPY proxy/package.json ./proxy/
COPY apps/api-nest/package.json ./apps/api-nest/
COPY apps/web/package.json ./apps/web/

COPY apps/api-nest/prisma ./apps/api-nest/prisma/

RUN --mount=type=cache,target=/root/.npm \
    npm ci

RUN npx prisma generate --schema=apps/api-nest/prisma/schema.prisma

ENV NODE_ENV=development
