FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/api-express/package.json ./apps/api-express/
RUN npm install

COPY . .

WORKDIR /app/apps/api-express

EXPOSE 3001
CMD ["npm", "run", "dev"]
